### ISSUE TITLE
Summoning rework proposal

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#265]
For discussion

---

Summoning abilities:

* Spirit Bear
* Plague Ward
* Mass Serpent Ward
* Primal Split (disabled)
* Death Ward
* Tombstone (disabled)
* Call of the Wild
* Force of Nature
* Mortal Strike (bugged)
* Chaotic Offering
* Summon Wolves
* Spawn Spiderlings
* Forge Spirit
* Summon Familiars
* Demonic Conversion
* Necronomicon / Book of the Dead

---

### Current summoning system

* Some summons are teleported along with the user to/from round arenas: spirit bear, visage familiars (?), etc.
* Some summons' scaling is a fraction of the above (usually multi-summon abilities like mass serpent ward)
* Some summoning skills' scaling doesn't work, some summoning skills are extremely useless

### Mask/Hood/Crown of the Dominator

These items grant a specific list of summons bonuses based on the summons' base stats and the caster's attributes:
+1.2/1.8/2.4% health per owner STR
+1.0/1.5/2.0% damage per owner INT
+0.6/0.8/1.0 attack speed per owner AGI
+0.06/0.08/0.1 armor per owner AGI

### High Summoner innate ability

* Increases summoning items' effect by 20%

### Scroll of summoning

3000 gold. Unlearns a random ability, and learns a random summoning ability in its place.

---

### Proposed summoning system

* Spirit Bear and Summon Familiars' summons follow the player into duels and rounds (and recover health in the fountain, and are invulnerable in the fountain).
* Instead of having fixed base stats, summons scale based on their user's stats by default.
* Each summon has its own scaling, based on the skill's intended flavor and usage.

Some examples (numbers are only rough ideas):

**Spirit Bear**
 * Health: 200/600/1000/1400 + 25/30/35/40x owner STR
 * Damage: 20/40/60/80 + 1.5x owner INT
 * Armor: owner's base armor + 2/4/6/8
 * Magic Resistance: 25%
 * Can equip items
 * Has its own abilities (as normal spirit bear)

**Plague Ward**
 * Health: 100 + 0/2/4/6x owner STR
 * Damage: 10/20/30/40 + 0.25x owner INT
 * Armor: 50% of owner's base armor
 * Magic Resistance: 100%
 * Has poison sting
 * Is spell immune

**Summon Wolves**
 * Health: 200 + 0/3/6/10x owner STR
 * Damage: 15/30/45/60 + 0.5x owner INT
 * Armor: 50% of owner's base armor + 1/2/3/4
 * Magic Resistance: 50%
 * +40/60/80/100 attack speed
 * Wolves have their own abilities (as normal wolves)

**Death Ward**
 * Health, armor, magic resistance: invulnerable
 * Damage: 50/75/100 + 0.75x owner INT
 * Benefits from owner's attack modifiers
 * 0.3 BAT

### Helm of the Dominator

Re-enabled and reworked.

Eaglesong + Mystic Staff + Reaver (8700 gold)

+30 to all attributes

**Copycat** (passive): at the start of a round, summon a clone of a random creep from that round to your side. When summoning Ancient creeps or bosses, the clone is weaker than the original. The clone dies at the end of the round.

### Mask of the Dominator

Mystic Staff + Hyperstone + 700 gold recipe (5400 gold)

+ 35 intelligence
+ 60 attack speed

**Dominator's Might** (passive): Grants your summons +50% damage and +50 attack speed. Can stack.

### Hood of the Dominator

Reaver + Platemail + 1000 gold recipe (5400 gold)

+ 35 strength
+ 15 armor

**Dominator's Visage** (passive): Grants your summons +100% health and +10 armor. Can stack.

### Crown of the Dominator

Mask of the Dominator + Hood of the Dominator + Octarine Core (16700 gold)

+ 70 strength
+ 70 intelligence
+ 70 attack speed
+ 15 armor
+ 25% cooldown reduction (unstackable)

**Dominator's Reign** (passive): Grants your summons +50% damage, +50 attack speed, +100% health, and +10 armor. Can stack.

**Dominator's Celerity** (passive): Refreshes all your summoning abilities' cooldowns at the start of every round.

**Life Link** (passive): 25% of all damage you deal, and 15% of all damage your summons deal, is converted to healing to all of you. The effect is reduced to 10/10% when damaging creeps.

### Scroll of summoning

3000 gold. Removes a random non-summoning ability, and learns a random summoning ability in its place. Has no effect and is not consumed if all you have are summoning abilities.

### High Summoner innate ability

* Grants all your summons +30% health and damage.

**Comment by Draze22** [comment]
It feels a lot simpler for both the dev team and players to buff and nerf summon abilities where appropriate and have summons scale as normal with maybe a slight rework of the scaling (armour is a bit low imo).

Having the scaling be part of the ability means that summons will have their power spike much earlier in the game which could be fun but would likely be very difficult to balance.

I like your idea of having multiple items catered specifically to summon builds but think they should be kept separate from each other and not combine. That way players doing summon builds have more choices of how they want to scale their summons rather than mostly just buying all stat items (lets them focus on damage, attack speed, health, armour, lifesteal etc). 

Various items that could have upgrades for summon builds are: crimson guard (damage block), pipe (magic resistance/block), vlads (lifesteal), helm of the dominator (damage) (separate from crown of the dominator), drums (attack speed), assault cuirass (armour), solar crest (larger buff for 1 unit) and guardian greaves (health regen and healing).

Currently most of these items aren't worth buying for summon builds because they're quite cheap and therefor take up a slot that is currently better used by yet another crown of the dominator. Giving these items upgrades would allow summon builds to be customized more easily and give them greater ability to scale into the late game.

**Comment by darklordabc** [comment]
I assume this is now defunct because of the new rework.
