### ISSUE TITLE
Add chat command to test end game states in live games

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#368]
We need a way to test end game conditions faster than waiting through a whole game
We should add some chat command to beckons the end faster somehow
So we can test in live games
Maybe a command that removes all aegis, and adds loser debuff each round?
Or just the loser debuff thing

**Comment by fcalife** [comment]
Lots of debug commands have been added since. Personally I have no trouble testing what I need using them.

["-help"] = "Shows this list",
["-ra"] = "Shows the random hero selection screen",
["-redraw"] = "Opens the reroll ability menu",
["-imba"] = "Gives you a magic missile ability which does 1 million damage and has no cooldown",
["-blink"] = "Gives you a global blink ability with no cooldown",
["-<ability_name>"] = "Gives you an ability eg. -dazzle_bad_juju",
["-<item_name>"] = "Gives you an item eg. -item_blink",
["-hero <hero_name>"] = "Changes your hero, BUGGY eg. -tinker",
["-round <number>"] = "Starts a certain round",
["-repeat <number>"] = "Repeats this round multiple times",
["-curse <number>"] = "Gives you X number of curse stacks, buggy with UI",
["-par"] = "Creates a particle",
["-con"] = "Prints connection state",
["-li"] = "Prints current items",
["-lm"] = "Lists all modifiers on this hero",
["-la <true/false>"] = "Lists all abilities on this hero, '-la true' for more detail",
["-rg"] = "Report gold",
["-uh"] = "Unhide abilities",
["-rr"] = "Reloads scripts, VERY BUGGY",
["-allup <number>"] = "Gives all bots X experience",
["-refresh"] = "Refreshes ability charges",
["-position"] = "Prints hero position",
["-options"] = "Change options to default",
["-debug_stats"] = "Prints info on timers, entities, creatures and frame time (ideal is 0.033333335071802)"

Leaving this open for suggestions of more commands, closing otherwise.

**Comment by darklordabc** [comment]
I want a command to end live games prematurely, admittedly seems less important now.

**Comment by fcalife** [comment]
Added -endgame command, immediately ends the game with your team as the winner.
