### ISSUE TITLE
Issue with retraining books

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#409]
![image](https://user-images.githubusercontent.com/63279022/89001716-54102a00-d33e-11ea-9c4a-190575c086ee.png)

**Comment by darklordabc** [comment]
![image](https://user-images.githubusercontent.com/16277198/89075658-0dfcaa00-d3c2-11ea-892f-55734ef82ac6.png)
https://discordapp.com/channels/694060511209324585/694440472273354762/738837268311179277

**Comment by fcalife** [comment]
I assume this has to do with the previous summoner book bug.

Removing/adding new spells in general breaks if you do it too fast, because though the game doesn't show the removed abilities on your skill bar, they stay there for 10 seconds, to prevent bugs related to hard-removing skills instantly. This can cause the ability count limit (32) to be hit, and when this happens, the whole system just comes crashing down hard.

This should be impossible, however, with the new UI, since it has a significant delay when using books of retraining. I tried spamming them as hard as I could for a couple minutes, using 'discard' to make it faster, and never managed to reach this bug.

Closing this one due to _**assuming**_ it is no longer practical in a real game.
