### ISSUE TITLE
Luna sometimes can't use eclipse when she buys aghs

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#478]
This is the second report of this happening.

![image](https://user-images.githubusercontent.com/63279022/98063666-9fd5f080-1ea4-11eb-8b69-c3f127bcf455.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch

**Comment by fcalife** [comment]
The fix in https://github.com/dota2unofficial/custom_hero_clash/commit/babda7b0ba94c885f1b94156e1930cd0df3105f9 wasn't complete, since it didn't allow casting the aghs spell on the ground (the vanilla behavior).

Fully fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/c46e5cf4e198ba107575636101be1e2cde2e7e31, repairing the vanilla casting behavior.
