### ISSUE TITLE
Record Early Leavers and present like in Chaos

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#500]
Prehaps a reward for players that make it to the end for 3 games, maybe some glory bonus?

**Comment by fcalife** [comment]
Working on this

**Comment by fcalife** [comment]
I couldn't figure out exactly how the chaos leaver detection works. I abandoned 4 games, and played 2 to the end, and it counted my 6 games correctly, but only gave me one early leaver score...

I also can't see anywhere in the code related to actually uploading this information to the server. It might be that the logic is on their web server instead of the dota lua, or I just couldn't find it.

I suggest implementing a karma system related to abandons:
 - New players start with 30 karma.
 - Playing a game to its natural end grants +10 karma.
 - Abandoning a game causes the player to lose 30 karma.
 - Players need at least 0 karma to earn any experience from playing.
 - Players at -50 karma or below are automatically muted on chat & voice.
 - Players at -100 karma or below are signaled as 'abandoners' in-game to other players.
 - Players with positive karma gain +1% bonus experience per 10 karma they have (capped at +10% at +100 karma)
 - Karma is capped at -150 / +100

An abandon is registered if the player simply abandons the game entirely, or stays disconnected for at least 5 minutes. The 5 minutes do not need to be continuous.

The following conditions exempt a player from getting an abandon:
 - They have already been eliminated;
 - 15 minutes of game have already elapsed;
 - A player from their team has already abandoned;
 - Any 3 other players have already abandoned.

**Comment by fcalife** [comment]
Early leaver detaction implemented in https://github.com/dota2unofficial/custom_hero_clash/commit/96af5951347da7bc3cd22eb144a4500fd5f0fd1f - will prevent players from earning fortune if they leave games early.
