### ISSUE TITLE
Jingu mastery can proc off of ward summons

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#562]
Jingu mastery can proc off of serpent wards and presumably plague wards too.

**Comment by fcalife** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/fe5761a4c6554e6e2063c41620c79be6aa5b4c69

Note that, according to the wiki:
![image](https://user-images.githubusercontent.com/7921728/101589976-4a6f9080-39c8-11eb-8448-62d630311d5e.png)

so the lifesteal still works against wards, but you will no longer gain stacks from attacking them.
