### ISSUE TITLE
Forged spirit with aghanim's scepter is bugged

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#579]
Forged spirit with aghanim's scepter isn't fully affected by crown of the dominator.

**Comment by fcalife** [comment]
From testing, this is a bug with the forge spirits (AD) ability. Upon purchasing a scepter, the spirit's damage reverts to its level 1 version (15 base damage instead of 90). Everything else (summon power included) then works as expected in such a scenario.

Suggested fix to the underlying issue is to remake forge spirits.
