### ISSUE TITLE
Pheonix fire spirits (with aghs) can't be swapped in duos since they're always active

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#608]
![image](https://user-images.githubusercontent.com/63279022/102680820-1d18b300-4210-11eb-9266-af529aa8af44.png)
![image](https://user-images.githubusercontent.com/63279022/102680823-230e9400-4210-11eb-95c7-d52965158603.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch

**Comment by fcalife** [comment]
Well, it's fixed, yeah

**Comment by fcalife** [comment]
The behavior on the ability is as follows:

- learn it without shard: works normally (non-shard behavior)
- buy shard after it is learned: does not work
- buy shard, *then* learn it: works normally (shard behavior)

There's probably a few abilities which behave like this. Need to make a list and have it so when a shard is purchased, they are unlearned/learned again in order to clean those behaviors.

To be fair, that likely belongs to another issue, not this one.
