### ISSUE TITLE
[7.28] Update custom abilities

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#631]
Go through the 7.28 patch notes and update any custom ability we currently use to reflect the changes from the patch.

┆Issue is synchronized with this [Trello card](https://trello.com/c/8bRkwpm4) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
- [ ] Borrowed time scepter duration from 5/6/7 to 6/7/8
- [ ] Tempest double +12s duration level 25 talent
- [ ] Counter helix now had agh's shard instead of talent for attacks proc (anyone know why we have a custom version of this it seems identical to the normal one)
- [ ] Infest scepter change (we should honestly just remove infest it doesn't fit into chc at all and theres still several bugs allowing players to become hidden forever)
- [ ] fiery soul attack speed from 40/55/70/85 to 40/60/80/100
- [ ] Hunter in the night needs rewriting due to new aghs shard working on bosses
- [ ] Fire spirits is currently unretrainable and untradeable with new aghs shard
- [ ] Flesh heap special effects from 8/10/12/14% to 12/14/16/18%
- [ ] Demonic purge scepter change and new shard
- [ ] Anchor smash aghs shard
- [ ] Tree grab cooldown from 25/20/15/10 to 16/14/12/10
- [ ] Decay manacost increased from 70/85/100/115 to 85/95/105/115
- [ ] Decay aghs shard
- [ ]

**Comment by Snoresville** [comment]
ongoing progress in https://github.com/dota2unofficial/custom_hero_clash/pull/631

**Comment by Snoresville** [comment]
complete fix of this issue should also solve https://github.com/dota2unofficial/custom_hero_clash_issues/issues/639

**Comment by Snoresville** [comment]
related issue: https://github.com/dota2unofficial/custom_hero_clash_issues/issues/671

**Comment by Snoresville** [comment]
Related branch has been merged
