### ISSUE TITLE
Multicast MegaThread

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#78]
Paste images of multicast bugging out abilities and items here

┆Issue is synchronized with this [Trello card](https://trello.com/c/RuRPLnsT) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
Rolling boulder 
![image](https://user-images.githubusercontent.com/50186248/78961016-391d6e00-7b33-11ea-8030-92d9ae071087.png)

**Comment by SanctusAnimus** [comment]
Heya that's my favourite one! (Jk I'll fix it, looks adorable tho)

**Comment by beepbeepboop** [comment]
NOT A BUG, but a suggestion, gonna add it to the multicast thread for cleanliness

Add firespirits (phoenix) and vambrace to the multicast blacklist

Reason:
vambrace is annoying I always hear people struggling in fountain trying to toggle their vambrace to int but then getting a 3 times multicast and it goes back to strength XD. I struggled with it too
For firespirits when you multicast it 4 times you lose all your hp, and its not even useful to have 16 firespirits because the attackspeed slow and damage from them doesnt even stack. It's more of a detriment to the player than it is useful**

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/79024130-5d298f80-7bc5-11ea-8b2d-d989cea4794c.png)
Bit debatable if it should or shouldn't multicast, although if it hits 2-4x as much because of it then it probably shouldnt

**Comment by SanctusAnimus** [comment]
We can switch it to target different enemies, or disable at all, what do you think

**Comment by AustraliaIsMyCity** [comment]
> We can switch it to target different enemies, or disable at all, what do you think

is it worth having a vote in the discord for this?

**Comment by SanctusAnimus** [comment]
not really, it's not a gamechanging mechanic or feature

**Comment by AustraliaIsMyCity** [comment]
disable it then

**Comment by dym-sh** [comment]
general rule of thumb: if it does not stack with refresher – it should not stuck with multicast

**Comment by AustraliaIsMyCity** [comment]
All channelled abilities bug out pretty hard with multicast (some lasting forever and other wacky stuff)

**Comment by AustraliaIsMyCity** [comment]
Both versions of bedlam can create phantom bedlams which last forever

**Comment by AustraliaIsMyCity** [comment]
Chakram multicasts and lasts forever

**Comment by Blasphemy-Incarnate** [comment]
Multicasting spirit siphon adds charges (needs confirmation).

**Comment by Blasphemy-Incarnate** [comment]
Multicasting refresher will refresh multiple times. Spamming instant cast abilities will allow you to use them multiple times, e.g. midas. Debatable whether this is considered a bug, but since it's a side effect of the multicast delay I don't see why refresher shouldn't be added to the blacklist. [Needs confirmation, but it seems likely]

**Comment by waylaidwanderer** [comment]
> Spamming instant cast abilities will allow you to use them multiple times, e.g. midas

I don't think Midas is a concern especially as you can multi-cast with it in the actual game as well (though the behavior is slightly different).

**Comment by AustraliaIsMyCity** [comment]
Song of the siren lasts forever if it multicasts

**Comment by Sheodar** [comment]
PA custom stifling dagger work strange

**Comment by AustraliaIsMyCity** [comment]
All toggles (null field specifically i know procs but shouldnt)

**Comment by dym-sh** [comment]
stackable consumables like smoke, dust, and sentries must never multicast

**Comment by dym-sh** [comment]
upgraded blinks should not multicast – having to wait for 4x blink animations and additionally travel a total of 4x the distance may lose some duels and even creep rounds

**Comment by Draze22** [comment]
This hasn't been used for a while so I'm closing it.

**Comment by dym-sh** [comment]
just to remind, necro2 was still mulicasting this week
